[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/summit"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/conference"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/people"
  to = "/team"
  status = 301
  force = true
